export const ITEM_CLASS_MAP: Record<string, string> = {
  'Sceptres': 'weapon.sceptre',
  'Wands': 'weapon.wand',
  'Staves': 'weapon.staff',
  'One Hand Axes': 'weapon.axe.1h',
  'Two Hand Axes': 'weapon.axe.2h',
  'One Hand Maces': 'weapon.mace.1h',
  'Two Hand Maces': 'weapon.mace.2h',
  'One Hand Swords': 'weapon.sword.1h',
  'Two Hand Swords': 'weapon.sword.2h',
  'Thrusting One Hand Swords': 'weapon.sword.thrusting.1h',
  'Bows': 'weapon.bow',
  'Claws': 'weapon.claw',
  'Daggers': 'weapon.dagger',
  'Rune Daggers': 'weapon.runedagger',
  'Warstaves': 'weapon.warstaff',
  'Body Armours': 'armour.chest',
  'Boots': 'armour.boots',
  'Gloves': 'armour.gloves',
  'Helmets': 'armour.helmet',
  'Shields': 'armour.shield',
  'Quivers': 'armour.quiver',
  'Amulets': 'accessory.amulet',
  'Rings': 'accessory.ring',
  'Belts': 'accessory.belt'
}; 
